### ISSUE TITLE
Getting error when trying to start training of LIF Model with TSEvents as input: ValueError: Input has wrong neuron dimension

### ISSUE THREAD

**Issue by fire-papaya** [synsense/rockpool#1]
I am trying to build simple network with two layers of LIF neurons of size 50 and 8 respectively with spike train input:

```
# - Define the network size
input_size = 50
hidden_size = 50
output_size = 8

# - Build a sequential stack of modules
sequential_model = Sequential(
    LIF((input_size, hidden_size)),
    LIF((hidden_size, output_size))
)
```
then defining `TSEvent`:
```
input_spike_events = TSEvent(
    times=spikes[1],
    channels=spikes[0],
    t_start=0,
    t_stop=1000,
    num_channels=50
)
```
where `spikes` is `ndarray` of shape 2xN, with N - number of spike, `spikes[1]` - timepoint of spikes, and `spikes[0]` - respective spiking channels
```
print(input_spike_events)
``` 

produces:
```
non-periodic `TSEvent` object `unnamed` from t=0.0 to 1000.0. Channels: 50. 
Events: 244
```

But when I call:
```
output, new_state, _ = sequential_model(input_spike_events)
```
I get an error:
```
ValueError: Input has wrong neuron dimension. It is 2, must be 50
```

From what i see the issue is in `/rockpool/nn/modules/module.py` inside the function `_auto_batch`, line 763, which incorrectly derives `n_connections` based on `data.shape` instead of using `num_channels` parameter of `TSEvent` object

rockpool v2.4.2

**Comment by DylanMuir** [comment]
Hi @fire-papaya , sorry for my slow reply here.

Base Rockpool modules and networks expect `numpy` arrays as inputs. If you would like to use `TSEvent` objects, then you can convert your network to the TimeSeries API by calling `sequential_model.timed()`.

```python
sq_timed = sequential_model.timed()
output, new_state, _ = sq_timed(input_spike_events)
```

This should then work without error.
