### ISSUE TITLE
Import error:  import rockpool.devices.xylo.syns61201 as xylo   ValueError: type 'v' not supported

### ISSUE THREAD

**Issue by bbkrsddq11** [synsense/rockpool#14]
ERROR      Brian 2 encountered an unexpected error. If you think this is a bug in Brian 2, please report this issue either to the discourse forum at http://brian.discourse.group/, or to the issue tracker at https://github.com/brian-team/brian2/issues. Please include this file with debug information in your report: /tmp/brian_debug_mgl7bbpr.log  Additionally, you can also include a copy of the script that was run, available at: /tmp/brian_script_cafm6tji.py Thanks! [brian2]
Traceback (most recent call last):
  File "xylo.py", line 6, in <module>
    import rockpool.devices.xylo.syns61201 as xylo
  File "/home/jackal1/.local/lib/python3.8/site-packages/rockpool/devices/xylo/init.py", line 33, in <module>
    import rockpool.devices.xylo.syns61300 as pollen
  File "/home/jackal1/.local/lib/python3.8/site-packages/rockpool/devices/xylo/syns61300/init.py", line 42, in <module>
    from .xylo_samna import *
  File "/home/jackal1/.local/lib/python3.8/site-packages/rockpool/devices/xylo/syns61300/xylo_samna.py", line 25, in <module>
    from . import xylo_devkit_utils as hdkutils
  File "/home/jackal1/.local/lib/python3.8/site-packages/rockpool/devices/xylo/syns61300/xylo_devkit_utils.py", line 154, in <module>
    from ..syns61201.xa2_devkit_utils import find_xylo_a2_boards
  File "/home/jackal1/.local/lib/python3.8/site-packages/rockpool/devices/xylo/syns61201/init.py", line 39, in <module>
    from .xylo_samna import *
  File "/home/jackal1/.local/lib/python3.8/site-packages/rockpool/devices/xylo/syns61201/xylo_samna.py", line 25, in <module>
    from . import xa2_devkit_utils as hdkutils
  File "/home/jackal1/.local/lib/python3.8/site-packages/rockpool/devices/xylo/syns61201/xa2_devkit_utils.py", line 5, in <module>
    from ctypes.wintypes import INT
  File "/usr/lib/python3.8/ctypes/wintypes.py", line 20, in <module>
    class VARIANT_BOOL(ctypes._SimpleCData):
ValueError: type 'v' not supported
[10:08 AM]
Can anyone help me with this error?

**Comment by DylanMuir** [comment]
Hi @bbkrsddq11 , thanks for flagging this. We will fix this in the next release — in the meantime, you can comment out the import on File "/home/jackal1/.local/lib/python3.8/site-packages/rockpool/devices/xylo/syns61201/xa2_devkit_utils.py", line 5.
# from ctypes.wintypes import INT

**Comment by DylanMuir** [comment]
Please reopen if that does not resolve the error!

**Comment by bbkrsddq11** [comment]
XyloSim  with shape (16, 1000, 8)
[]
ERROR      Brian 2 encountered an unexpected error. If you think this is a bug in Brian 2, please report this issue either to the discourse forum at http://brian.discourse.group/, or to the issue tracker at https://github.com/brian-team/brian2/issues. Please include this file with debug information in your report: /tmp/brian_debug_csyfqchc.log  Additionally, you can also include a copy of the script that was run, available at: /tmp/brian_script_4ikrsit7.py Thanks! [brian2]
Traceback (most recent call last):
  File "sscfinalsimulation.py", line 513, in <module>
    assert len(hdks) > 0, 'The rest of this notebook needs a connected Xylo HDK.'
AssertionError: The rest of this notebook needs a connected Xylo HDK.
                                                                                                                                                                                                                                                                                                                                                                                                Dear Dr. Dylan, I followed your suggestions and ValueError get resolved. However, I got assertion error and saying Xylo HDK is not connected. I have connected the Xylo with the laptop but still I'm getting this error, I'm not sure why. Could you kindly give me some suggestion on this how I can resolve this issue?

**Comment by bbkrsddq11** [comment]
Dear Dr. Dylan, Thank you so much for your suggestion. I'm doing the same, as I'm running .py file using the linux terminal by starting a fresh python instance takes a long time to run the whole procedure each time. You have any suggestion on this?

**Comment by DylanMuir** [comment]
Hi @bbkrsddq11 , I don't quite understand. The error you posted `AssertionError: The rest of this notebook needs a connected Xylo HDK.` indicates that for some reason Rockpool cannot connect to the HDK.

Does the error occur every time, or only occasionally? Can you interact with the HDK in a notebook?
