### ISSUE TITLE
Training with JAX tutorial won't work because `optimizers` moved to `optax` 

### ISSUE THREAD

**Issue by aquaresima** [synsense/rockpool#2]
Hello,

JAX has moved the jax.experimental.optimizers to optax (see [here](
https://jax.readthedocs.io/en/latest/jax.example_libraries.optimizers.html))

And the vanilla installation of JAX won't give access to the experimental module.
Therefore, this [tutorial](https://synsense.gitlab.io/rockpool/tutorials/jax_lif_sgd.html#Training-the-network) breaks.

Solving it is not as simple as changing this:
`from jax.experimental.optimizers import adam`
 to this:
`from optax import adam`

because `optax` uses different functions to update the parameters. I ll try to solve it with my _null_ understanding of JAX and optax, if I come to a fix I ll post it here

I am using MacOS Ventura 13.0
Python 3.10.8
JAX Version: 0.3.25
optax Version: 0.1.4
rockpool Version 2.4.2

**Comment by aquaresima** [comment]
Ok, this will work.

I tried to be the most consistent with the structure of the tutorial and still reproduce the style in the optax [tutorial](https://optax.readthedocs.io/en/latest/optax-101.html?highlight=params#).

```
# - Useful imports
from tqdm.autonotebook import tqdm
from copy import deepcopy
from itertools import count

# -- Import an optimiser to use and initalise it
import jax
import optax

# create ADAM optimizer
optimizer = optax.adam(learning_rate=1e-2)

# initialize the optimizer state
params0 = copy.deepcopy(modFFwd.parameters())
opt_state = optimizer.init(modFFwd.parameters())

# - Get a compiled value-and-gradient function
loss_vgf = jax.jit(jax.value_and_grad(loss_mse))


# - Record the loss values over training iterations
loss_t = []
grad_t = []

num_epochs = 2000

# - Define step function: takes a single step of the optimiser
@jax.jit
def step(params: optax.Params, opt_state, input, target) -> optax.Params:
    loss_val, grads = loss_vgf(params, modFFwd, input, target)
    updates, opt_state = optimizer.update(grads, opt_state, params) # update the optimizer state
    params = optax.apply_updates(params, updates) # apply the updates to the parameters
    return params, opt_state, loss_val

# parameters and opt_state are updated in place and separately
input = input_sp_raster * input_scale
target = chirp
params, opt_state, _ =  step(params0, opt_state, input, target)
```

```
# - Loop over iterations
i_trial = count()
for _ in tqdm(range(num_epochs)):
    # - Get the loss value and gradients for this iteration and update the parameters
    params, opt_state, loss_value = step(params, opt_state, input, target)

    # - Keep track of the loss
    loss_t.append(loss_value)
```

**Comment by DylanMuir** [comment]
Hi @aquaresima , thanks for flagging this issue! We've fixed these tutorials and updated in the latest released version (5 mins ago).
