### ISSUE TITLE
The installation of brian

### ISSUE THREAD

**Issue by mosfe** [synsense/rockpool#4]
Hello
I have pip install rockpool[all] on my ubuntu18.04 desktop, and it has no error. However, the brian is not included in the backend models of Rockpool, thai is why?
![1665167a41655590fa27b03809e51fd](https://user-images.githubusercontent.com/95094143/224526276-21850b6c-cc28-4040-9977-5330ab37ad8e.jpg)

**Comment by DylanMuir** [comment]
Dear @mosfe, thanks for identifying this bug. We have fixed this in the `develop` branch, and will make a new release in the next week or two including this fix.

In the meantime, you can clone the repository and install locally with `pip install -e .`
