### ISSUE TITLE
Typos in rockpool-shd tutorial

### ISSUE THREAD

**Issue by mosfe** [synsense/rockpool#6]
Hello , when I read the document of rockpool, I find a problem in https://rockpool.ai/tutorials/rockpool-shd.html.
As shown in figure, the sample_T is set as 100, and the result I get is (100,20). However, in the following description, 
it is set as 250 twice, it troubled me a lot. Hope for your reply.
![image](https://user-images.githubusercontent.com/95094143/225241602-43189b10-c967-428f-bf34-fa7e49ee8a40.png)
![image](https://user-images.githubusercontent.com/95094143/225241687-e206d93d-018d-4e6d-9ec8-709171a51ad9.png)
![image](https://user-images.githubusercontent.com/95094143/225241736-aab43631-ec3b-432c-bf3c-69c21f64cb0c.png)

**Comment by DylanMuir** [comment]
Hi @mosfe, thanks for flagging these typos. We will fix them when updating the tutorial.

**Comment by DylanMuir** [comment]
Resolved in `develop`
